name: trading_bot_app
description: BTC Smart DCA Bot mobile dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  hooks_riverpod: ^3.2.1
  flutter_hooks: any
  riverpod_annotation: ^4.0.2
  dio: ^5.9.1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  riverpod_generator: ^4.0.3
  riverpod_lint: any

flutter:
  uses-material-design: true
